// <auto-generated />
namespace reddit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class connectionstringchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(connectionstringchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201704221534270_connectionstring change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
